/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as WorkbenchRouteImport } from './routes/workbench'
import { Route as CaseCaseIdRouteRouteImport } from './routes/case/$caseId/route'
import { Route as CompaniesIndexRouteImport } from './routes/companies/index'
import { Route as CompaniesOrganizationIdRouteImport } from './routes/companies/$organizationId'
import { Route as ContractorsIndexRouteImport } from './routes/contractors/index'
import { Route as ContractorsContractorIdRouteImport } from './routes/contractors/$contractorId'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as CaseCaseIdIndexRouteImport } from './routes/case/$caseId/index'
import { Route as CaseCaseIdChatRouteImport } from './routes/case/$caseId/chat'
import { Route as CaseCaseIdDossierRouteImport } from './routes/case/$caseId/dossier'
import { Route as CaseCaseIdInboxRouteImport } from './routes/case/$caseId/inbox'
import { Route as CaseCaseIdLedgerRouteImport } from './routes/case/$caseId/ledger'
import { Route as CaseCaseIdMandateRouteImport } from './routes/case/$caseId/mandate'
import { Route as CaseCaseIdRoadmapRouteImport } from './routes/case/$caseId/roadmap'
import { Route as IntakeCompanyOrganizationIdRouteImport } from './routes/intake/company/$organizationId'
import { Route as IntakeProductProductIdRouteImport } from './routes/intake/product/$productId'
import { Route as ProductsProductIdIndexRouteImport } from './routes/products/$productId/index'
import { Route as ProductsProductIdClassifyRouteImport } from './routes/products/$productId/classify'
import { Route as CaseCaseIdNodesNodeCodeRouteImport } from './routes/case/$caseId/nodes/$nodeCode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkbenchRoute = WorkbenchRouteImport.update({
  id: '/workbench',
  path: '/workbench',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseCaseIdRouteRoute = CaseCaseIdRouteRouteImport.update({
  id: '/case/$caseId',
  path: '/case/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesOrganizationIdRoute = CompaniesOrganizationIdRouteImport.update({
  id: '/companies/$organizationId',
  path: '/companies/$organizationId',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorsIndexRoute = ContractorsIndexRouteImport.update({
  id: '/contractors/',
  path: '/contractors/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorsContractorIdRoute = ContractorsContractorIdRouteImport.update({
  id: '/contractors/$contractorId',
  path: '/contractors/$contractorId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseCaseIdIndexRoute = CaseCaseIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaseCaseIdRouteRoute,
} as any)
const CaseCaseIdChatRoute = CaseCaseIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => CaseCaseIdRouteRoute,
} as any)
const CaseCaseIdDossierRoute = CaseCaseIdDossierRouteImport.update({
  id: '/dossier',
  path: '/dossier',
  getParentRoute: () => CaseCaseIdRouteRoute,
} as any)
const CaseCaseIdInboxRoute = CaseCaseIdInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => CaseCaseIdRouteRoute,
} as any)
const CaseCaseIdLedgerRoute = CaseCaseIdLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => CaseCaseIdRouteRoute,
} as any)
const CaseCaseIdMandateRoute = CaseCaseIdMandateRouteImport.update({
  id: '/mandate',
  path: '/mandate',
  getParentRoute: () => CaseCaseIdRouteRoute,
} as any)
const CaseCaseIdRoadmapRoute = CaseCaseIdRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => CaseCaseIdRouteRoute,
} as any)
const IntakeCompanyOrganizationIdRoute =
  IntakeCompanyOrganizationIdRouteImport.update({
    id: '/intake/company/$organizationId',
    path: '/intake/company/$organizationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const IntakeProductProductIdRoute = IntakeProductProductIdRouteImport.update({
  id: '/intake/product/$productId',
  path: '/intake/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdIndexRoute = ProductsProductIdIndexRouteImport.update({
  id: '/products/$productId/',
  path: '/products/$productId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdClassifyRoute =
  ProductsProductIdClassifyRouteImport.update({
    id: '/products/$productId/classify',
    path: '/products/$productId/classify',
    getParentRoute: () => rootRouteImport,
  } as any)
const CaseCaseIdNodesNodeCodeRoute = CaseCaseIdNodesNodeCodeRouteImport.update({
  id: '/nodes/$nodeCode',
  path: '/nodes/$nodeCode',
  getParentRoute: () => CaseCaseIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/automation': typeof AutomationRoute
  '/documents': typeof DocumentsRoute
  '/messages': typeof MessagesRoute
  '/payments': typeof PaymentsRoute
  '/workbench': typeof WorkbenchRoute
  '/case/$caseId': typeof CaseCaseIdRouteRouteWithChildren
  '/companies/$organizationId': typeof CompaniesOrganizationIdRoute
  '/contractors/$contractorId': typeof ContractorsContractorIdRoute
  '/companies/': typeof CompaniesIndexRoute
  '/contractors/': typeof ContractorsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/case/$caseId/chat': typeof CaseCaseIdChatRoute
  '/case/$caseId/dossier': typeof CaseCaseIdDossierRoute
  '/case/$caseId/inbox': typeof CaseCaseIdInboxRoute
  '/case/$caseId/ledger': typeof CaseCaseIdLedgerRoute
  '/case/$caseId/mandate': typeof CaseCaseIdMandateRoute
  '/case/$caseId/roadmap': typeof CaseCaseIdRoadmapRoute
  '/intake/company/$organizationId': typeof IntakeCompanyOrganizationIdRoute
  '/intake/product/$productId': typeof IntakeProductProductIdRoute
  '/products/$productId/classify': typeof ProductsProductIdClassifyRoute
  '/case/$caseId/': typeof CaseCaseIdIndexRoute
  '/products/$productId/': typeof ProductsProductIdIndexRoute
  '/case/$caseId/nodes/$nodeCode': typeof CaseCaseIdNodesNodeCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automation': typeof AutomationRoute
  '/documents': typeof DocumentsRoute
  '/messages': typeof MessagesRoute
  '/payments': typeof PaymentsRoute
  '/workbench': typeof WorkbenchRoute
  '/companies/$organizationId': typeof CompaniesOrganizationIdRoute
  '/contractors/$contractorId': typeof ContractorsContractorIdRoute
  '/companies': typeof CompaniesIndexRoute
  '/contractors': typeof ContractorsIndexRoute
  '/products': typeof ProductsIndexRoute
  '/case/$caseId/chat': typeof CaseCaseIdChatRoute
  '/case/$caseId/dossier': typeof CaseCaseIdDossierRoute
  '/case/$caseId/inbox': typeof CaseCaseIdInboxRoute
  '/case/$caseId/ledger': typeof CaseCaseIdLedgerRoute
  '/case/$caseId/mandate': typeof CaseCaseIdMandateRoute
  '/case/$caseId/roadmap': typeof CaseCaseIdRoadmapRoute
  '/intake/company/$organizationId': typeof IntakeCompanyOrganizationIdRoute
  '/intake/product/$productId': typeof IntakeProductProductIdRoute
  '/products/$productId/classify': typeof ProductsProductIdClassifyRoute
  '/case/$caseId': typeof CaseCaseIdIndexRoute
  '/products/$productId': typeof ProductsProductIdIndexRoute
  '/case/$caseId/nodes/$nodeCode': typeof CaseCaseIdNodesNodeCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/automation': typeof AutomationRoute
  '/documents': typeof DocumentsRoute
  '/messages': typeof MessagesRoute
  '/payments': typeof PaymentsRoute
  '/workbench': typeof WorkbenchRoute
  '/case/$caseId': typeof CaseCaseIdRouteRouteWithChildren
  '/companies/$organizationId': typeof CompaniesOrganizationIdRoute
  '/contractors/$contractorId': typeof ContractorsContractorIdRoute
  '/companies/': typeof CompaniesIndexRoute
  '/contractors/': typeof ContractorsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/case/$caseId/chat': typeof CaseCaseIdChatRoute
  '/case/$caseId/dossier': typeof CaseCaseIdDossierRoute
  '/case/$caseId/inbox': typeof CaseCaseIdInboxRoute
  '/case/$caseId/ledger': typeof CaseCaseIdLedgerRoute
  '/case/$caseId/mandate': typeof CaseCaseIdMandateRoute
  '/case/$caseId/roadmap': typeof CaseCaseIdRoadmapRoute
  '/intake/company/$organizationId': typeof IntakeCompanyOrganizationIdRoute
  '/intake/product/$productId': typeof IntakeProductProductIdRoute
  '/products/$productId/classify': typeof ProductsProductIdClassifyRoute
  '/case/$caseId/': typeof CaseCaseIdIndexRoute
  '/products/$productId/': typeof ProductsProductIdIndexRoute
  '/case/$caseId/nodes/$nodeCode': typeof CaseCaseIdNodesNodeCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/automation'
    | '/documents'
    | '/messages'
    | '/payments'
    | '/workbench'
    | '/case/$caseId'
    | '/companies/$organizationId'
    | '/contractors/$contractorId'
    | '/companies/'
    | '/contractors/'
    | '/products/'
    | '/case/$caseId/chat'
    | '/case/$caseId/dossier'
    | '/case/$caseId/inbox'
    | '/case/$caseId/ledger'
    | '/case/$caseId/mandate'
    | '/case/$caseId/roadmap'
    | '/intake/company/$organizationId'
    | '/intake/product/$productId'
    | '/products/$productId/classify'
    | '/case/$caseId/'
    | '/products/$productId/'
    | '/case/$caseId/nodes/$nodeCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/automation'
    | '/documents'
    | '/messages'
    | '/payments'
    | '/workbench'
    | '/companies/$organizationId'
    | '/contractors/$contractorId'
    | '/companies'
    | '/contractors'
    | '/products'
    | '/case/$caseId/chat'
    | '/case/$caseId/dossier'
    | '/case/$caseId/inbox'
    | '/case/$caseId/ledger'
    | '/case/$caseId/mandate'
    | '/case/$caseId/roadmap'
    | '/intake/company/$organizationId'
    | '/intake/product/$productId'
    | '/products/$productId/classify'
    | '/case/$caseId'
    | '/products/$productId'
    | '/case/$caseId/nodes/$nodeCode'
  id:
    | '__root__'
    | '/'
    | '/automation'
    | '/documents'
    | '/messages'
    | '/payments'
    | '/workbench'
    | '/case/$caseId'
    | '/companies/$organizationId'
    | '/contractors/$contractorId'
    | '/companies/'
    | '/contractors/'
    | '/products/'
    | '/case/$caseId/chat'
    | '/case/$caseId/dossier'
    | '/case/$caseId/inbox'
    | '/case/$caseId/ledger'
    | '/case/$caseId/mandate'
    | '/case/$caseId/roadmap'
    | '/intake/company/$organizationId'
    | '/intake/product/$productId'
    | '/products/$productId/classify'
    | '/case/$caseId/'
    | '/products/$productId/'
    | '/case/$caseId/nodes/$nodeCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutomationRoute: typeof AutomationRoute
  DocumentsRoute: typeof DocumentsRoute
  MessagesRoute: typeof MessagesRoute
  PaymentsRoute: typeof PaymentsRoute
  WorkbenchRoute: typeof WorkbenchRoute
  CaseCaseIdRouteRoute: typeof CaseCaseIdRouteRouteWithChildren
  CompaniesOrganizationIdRoute: typeof CompaniesOrganizationIdRoute
  ContractorsContractorIdRoute: typeof ContractorsContractorIdRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
  ContractorsIndexRoute: typeof ContractorsIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  IntakeCompanyOrganizationIdRoute: typeof IntakeCompanyOrganizationIdRoute
  IntakeProductProductIdRoute: typeof IntakeProductProductIdRoute
  ProductsProductIdClassifyRoute: typeof ProductsProductIdClassifyRoute
  ProductsProductIdIndexRoute: typeof ProductsProductIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workbench': {
      id: '/workbench'
      path: '/workbench'
      fullPath: '/workbench'
      preLoaderRoute: typeof WorkbenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case/$caseId': {
      id: '/case/$caseId'
      path: '/case/$caseId'
      fullPath: '/case/$caseId'
      preLoaderRoute: typeof CaseCaseIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$organizationId': {
      id: '/companies/$organizationId'
      path: '/companies/$organizationId'
      fullPath: '/companies/$organizationId'
      preLoaderRoute: typeof CompaniesOrganizationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractors/': {
      id: '/contractors/'
      path: '/contractors'
      fullPath: '/contractors/'
      preLoaderRoute: typeof ContractorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractors/$contractorId': {
      id: '/contractors/$contractorId'
      path: '/contractors/$contractorId'
      fullPath: '/contractors/$contractorId'
      preLoaderRoute: typeof ContractorsContractorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case/$caseId/': {
      id: '/case/$caseId/'
      path: '/'
      fullPath: '/case/$caseId/'
      preLoaderRoute: typeof CaseCaseIdIndexRouteImport
      parentRoute: typeof CaseCaseIdRouteRoute
    }
    '/case/$caseId/chat': {
      id: '/case/$caseId/chat'
      path: '/chat'
      fullPath: '/case/$caseId/chat'
      preLoaderRoute: typeof CaseCaseIdChatRouteImport
      parentRoute: typeof CaseCaseIdRouteRoute
    }
    '/case/$caseId/dossier': {
      id: '/case/$caseId/dossier'
      path: '/dossier'
      fullPath: '/case/$caseId/dossier'
      preLoaderRoute: typeof CaseCaseIdDossierRouteImport
      parentRoute: typeof CaseCaseIdRouteRoute
    }
    '/case/$caseId/inbox': {
      id: '/case/$caseId/inbox'
      path: '/inbox'
      fullPath: '/case/$caseId/inbox'
      preLoaderRoute: typeof CaseCaseIdInboxRouteImport
      parentRoute: typeof CaseCaseIdRouteRoute
    }
    '/case/$caseId/ledger': {
      id: '/case/$caseId/ledger'
      path: '/ledger'
      fullPath: '/case/$caseId/ledger'
      preLoaderRoute: typeof CaseCaseIdLedgerRouteImport
      parentRoute: typeof CaseCaseIdRouteRoute
    }
    '/case/$caseId/mandate': {
      id: '/case/$caseId/mandate'
      path: '/mandate'
      fullPath: '/case/$caseId/mandate'
      preLoaderRoute: typeof CaseCaseIdMandateRouteImport
      parentRoute: typeof CaseCaseIdRouteRoute
    }
    '/case/$caseId/roadmap': {
      id: '/case/$caseId/roadmap'
      path: '/roadmap'
      fullPath: '/case/$caseId/roadmap'
      preLoaderRoute: typeof CaseCaseIdRoadmapRouteImport
      parentRoute: typeof CaseCaseIdRouteRoute
    }
    '/intake/company/$organizationId': {
      id: '/intake/company/$organizationId'
      path: '/intake/company/$organizationId'
      fullPath: '/intake/company/$organizationId'
      preLoaderRoute: typeof IntakeCompanyOrganizationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/product/$productId': {
      id: '/intake/product/$productId'
      path: '/intake/product/$productId'
      fullPath: '/intake/product/$productId'
      preLoaderRoute: typeof IntakeProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId/': {
      id: '/products/$productId/'
      path: '/products/$productId'
      fullPath: '/products/$productId/'
      preLoaderRoute: typeof ProductsProductIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId/classify': {
      id: '/products/$productId/classify'
      path: '/products/$productId/classify'
      fullPath: '/products/$productId/classify'
      preLoaderRoute: typeof ProductsProductIdClassifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case/$caseId/nodes/$nodeCode': {
      id: '/case/$caseId/nodes/$nodeCode'
      path: '/nodes/$nodeCode'
      fullPath: '/case/$caseId/nodes/$nodeCode'
      preLoaderRoute: typeof CaseCaseIdNodesNodeCodeRouteImport
      parentRoute: typeof CaseCaseIdRouteRoute
    }
  }
}

interface CaseCaseIdRouteRouteChildren {
  CaseCaseIdChatRoute: typeof CaseCaseIdChatRoute
  CaseCaseIdDossierRoute: typeof CaseCaseIdDossierRoute
  CaseCaseIdInboxRoute: typeof CaseCaseIdInboxRoute
  CaseCaseIdLedgerRoute: typeof CaseCaseIdLedgerRoute
  CaseCaseIdMandateRoute: typeof CaseCaseIdMandateRoute
  CaseCaseIdRoadmapRoute: typeof CaseCaseIdRoadmapRoute
  CaseCaseIdIndexRoute: typeof CaseCaseIdIndexRoute
  CaseCaseIdNodesNodeCodeRoute: typeof CaseCaseIdNodesNodeCodeRoute
}

const CaseCaseIdRouteRouteChildren: CaseCaseIdRouteRouteChildren = {
  CaseCaseIdChatRoute: CaseCaseIdChatRoute,
  CaseCaseIdDossierRoute: CaseCaseIdDossierRoute,
  CaseCaseIdInboxRoute: CaseCaseIdInboxRoute,
  CaseCaseIdLedgerRoute: CaseCaseIdLedgerRoute,
  CaseCaseIdMandateRoute: CaseCaseIdMandateRoute,
  CaseCaseIdRoadmapRoute: CaseCaseIdRoadmapRoute,
  CaseCaseIdIndexRoute: CaseCaseIdIndexRoute,
  CaseCaseIdNodesNodeCodeRoute: CaseCaseIdNodesNodeCodeRoute,
}

const CaseCaseIdRouteRouteWithChildren = CaseCaseIdRouteRoute._addFileChildren(
  CaseCaseIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutomationRoute: AutomationRoute,
  DocumentsRoute: DocumentsRoute,
  MessagesRoute: MessagesRoute,
  PaymentsRoute: PaymentsRoute,
  WorkbenchRoute: WorkbenchRoute,
  CaseCaseIdRouteRoute: CaseCaseIdRouteRouteWithChildren,
  CompaniesOrganizationIdRoute: CompaniesOrganizationIdRoute,
  ContractorsContractorIdRoute: ContractorsContractorIdRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
  ContractorsIndexRoute: ContractorsIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  IntakeCompanyOrganizationIdRoute: IntakeCompanyOrganizationIdRoute,
  IntakeProductProductIdRoute: IntakeProductProductIdRoute,
  ProductsProductIdClassifyRoute: ProductsProductIdClassifyRoute,
  ProductsProductIdIndexRoute: ProductsProductIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
