/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaseCaseIdRouteRouteImport } from './routes/case/$caseId/route'
import { Route as CaseCaseIdIndexRouteImport } from './routes/case/$caseId/index'
import { Route as CaseCaseIdChatRouteImport } from './routes/case/$caseId/chat'
import { Route as CaseCaseIdDossierRouteImport } from './routes/case/$caseId/dossier'
import { Route as CaseCaseIdInboxRouteImport } from './routes/case/$caseId/inbox'
import { Route as CaseCaseIdLedgerRouteImport } from './routes/case/$caseId/ledger'
import { Route as CaseCaseIdMandateRouteImport } from './routes/case/$caseId/mandate'
import { Route as CaseCaseIdRoadmapRouteImport } from './routes/case/$caseId/roadmap'
import { Route as IntakeCompanyOrganizationIdRouteImport } from './routes/intake/company/$organizationId'
import { Route as IntakeProductProductIdRouteImport } from './routes/intake/product/$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseCaseIdRouteRoute = CaseCaseIdRouteRouteImport.update({
  id: '/case/$caseId',
  path: '/case/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseCaseIdIndexRoute = CaseCaseIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaseCaseIdRouteRoute,
} as any)
const CaseCaseIdChatRoute = CaseCaseIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => CaseCaseIdRouteRoute,
} as any)
const CaseCaseIdDossierRoute = CaseCaseIdDossierRouteImport.update({
  id: '/dossier',
  path: '/dossier',
  getParentRoute: () => CaseCaseIdRouteRoute,
} as any)
const CaseCaseIdInboxRoute = CaseCaseIdInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => CaseCaseIdRouteRoute,
} as any)
const CaseCaseIdLedgerRoute = CaseCaseIdLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => CaseCaseIdRouteRoute,
} as any)
const CaseCaseIdMandateRoute = CaseCaseIdMandateRouteImport.update({
  id: '/mandate',
  path: '/mandate',
  getParentRoute: () => CaseCaseIdRouteRoute,
} as any)
const CaseCaseIdRoadmapRoute = CaseCaseIdRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => CaseCaseIdRouteRoute,
} as any)
const IntakeCompanyOrganizationIdRoute =
  IntakeCompanyOrganizationIdRouteImport.update({
    id: '/intake/company/$organizationId',
    path: '/intake/company/$organizationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const IntakeProductProductIdRoute = IntakeProductProductIdRouteImport.update({
  id: '/intake/product/$productId',
  path: '/intake/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/case/$caseId': typeof CaseCaseIdRouteRouteWithChildren
  '/case/$caseId/chat': typeof CaseCaseIdChatRoute
  '/case/$caseId/dossier': typeof CaseCaseIdDossierRoute
  '/case/$caseId/inbox': typeof CaseCaseIdInboxRoute
  '/case/$caseId/ledger': typeof CaseCaseIdLedgerRoute
  '/case/$caseId/mandate': typeof CaseCaseIdMandateRoute
  '/case/$caseId/roadmap': typeof CaseCaseIdRoadmapRoute
  '/intake/company/$organizationId': typeof IntakeCompanyOrganizationIdRoute
  '/intake/product/$productId': typeof IntakeProductProductIdRoute
  '/case/$caseId/': typeof CaseCaseIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/case/$caseId/chat': typeof CaseCaseIdChatRoute
  '/case/$caseId/dossier': typeof CaseCaseIdDossierRoute
  '/case/$caseId/inbox': typeof CaseCaseIdInboxRoute
  '/case/$caseId/ledger': typeof CaseCaseIdLedgerRoute
  '/case/$caseId/mandate': typeof CaseCaseIdMandateRoute
  '/case/$caseId/roadmap': typeof CaseCaseIdRoadmapRoute
  '/intake/company/$organizationId': typeof IntakeCompanyOrganizationIdRoute
  '/intake/product/$productId': typeof IntakeProductProductIdRoute
  '/case/$caseId': typeof CaseCaseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/case/$caseId': typeof CaseCaseIdRouteRouteWithChildren
  '/case/$caseId/chat': typeof CaseCaseIdChatRoute
  '/case/$caseId/dossier': typeof CaseCaseIdDossierRoute
  '/case/$caseId/inbox': typeof CaseCaseIdInboxRoute
  '/case/$caseId/ledger': typeof CaseCaseIdLedgerRoute
  '/case/$caseId/mandate': typeof CaseCaseIdMandateRoute
  '/case/$caseId/roadmap': typeof CaseCaseIdRoadmapRoute
  '/intake/company/$organizationId': typeof IntakeCompanyOrganizationIdRoute
  '/intake/product/$productId': typeof IntakeProductProductIdRoute
  '/case/$caseId/': typeof CaseCaseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/case/$caseId'
    | '/case/$caseId/chat'
    | '/case/$caseId/dossier'
    | '/case/$caseId/inbox'
    | '/case/$caseId/ledger'
    | '/case/$caseId/mandate'
    | '/case/$caseId/roadmap'
    | '/intake/company/$organizationId'
    | '/intake/product/$productId'
    | '/case/$caseId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/case/$caseId/chat'
    | '/case/$caseId/dossier'
    | '/case/$caseId/inbox'
    | '/case/$caseId/ledger'
    | '/case/$caseId/mandate'
    | '/case/$caseId/roadmap'
    | '/intake/company/$organizationId'
    | '/intake/product/$productId'
    | '/case/$caseId'
  id:
    | '__root__'
    | '/'
    | '/case/$caseId'
    | '/case/$caseId/chat'
    | '/case/$caseId/dossier'
    | '/case/$caseId/inbox'
    | '/case/$caseId/ledger'
    | '/case/$caseId/mandate'
    | '/case/$caseId/roadmap'
    | '/intake/company/$organizationId'
    | '/intake/product/$productId'
    | '/case/$caseId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaseCaseIdRouteRoute: typeof CaseCaseIdRouteRouteWithChildren
  IntakeCompanyOrganizationIdRoute: typeof IntakeCompanyOrganizationIdRoute
  IntakeProductProductIdRoute: typeof IntakeProductProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case/$caseId': {
      id: '/case/$caseId'
      path: '/case/$caseId'
      fullPath: '/case/$caseId'
      preLoaderRoute: typeof CaseCaseIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case/$caseId/': {
      id: '/case/$caseId/'
      path: '/'
      fullPath: '/case/$caseId/'
      preLoaderRoute: typeof CaseCaseIdIndexRouteImport
      parentRoute: typeof CaseCaseIdRouteRoute
    }
    '/case/$caseId/chat': {
      id: '/case/$caseId/chat'
      path: '/chat'
      fullPath: '/case/$caseId/chat'
      preLoaderRoute: typeof CaseCaseIdChatRouteImport
      parentRoute: typeof CaseCaseIdRouteRoute
    }
    '/case/$caseId/dossier': {
      id: '/case/$caseId/dossier'
      path: '/dossier'
      fullPath: '/case/$caseId/dossier'
      preLoaderRoute: typeof CaseCaseIdDossierRouteImport
      parentRoute: typeof CaseCaseIdRouteRoute
    }
    '/case/$caseId/inbox': {
      id: '/case/$caseId/inbox'
      path: '/inbox'
      fullPath: '/case/$caseId/inbox'
      preLoaderRoute: typeof CaseCaseIdInboxRouteImport
      parentRoute: typeof CaseCaseIdRouteRoute
    }
    '/case/$caseId/ledger': {
      id: '/case/$caseId/ledger'
      path: '/ledger'
      fullPath: '/case/$caseId/ledger'
      preLoaderRoute: typeof CaseCaseIdLedgerRouteImport
      parentRoute: typeof CaseCaseIdRouteRoute
    }
    '/case/$caseId/mandate': {
      id: '/case/$caseId/mandate'
      path: '/mandate'
      fullPath: '/case/$caseId/mandate'
      preLoaderRoute: typeof CaseCaseIdMandateRouteImport
      parentRoute: typeof CaseCaseIdRouteRoute
    }
    '/case/$caseId/roadmap': {
      id: '/case/$caseId/roadmap'
      path: '/roadmap'
      fullPath: '/case/$caseId/roadmap'
      preLoaderRoute: typeof CaseCaseIdRoadmapRouteImport
      parentRoute: typeof CaseCaseIdRouteRoute
    }
    '/intake/company/$organizationId': {
      id: '/intake/company/$organizationId'
      path: '/intake/company/$organizationId'
      fullPath: '/intake/company/$organizationId'
      preLoaderRoute: typeof IntakeCompanyOrganizationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/product/$productId': {
      id: '/intake/product/$productId'
      path: '/intake/product/$productId'
      fullPath: '/intake/product/$productId'
      preLoaderRoute: typeof IntakeProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CaseCaseIdRouteRouteChildren {
  CaseCaseIdChatRoute: typeof CaseCaseIdChatRoute
  CaseCaseIdDossierRoute: typeof CaseCaseIdDossierRoute
  CaseCaseIdInboxRoute: typeof CaseCaseIdInboxRoute
  CaseCaseIdLedgerRoute: typeof CaseCaseIdLedgerRoute
  CaseCaseIdMandateRoute: typeof CaseCaseIdMandateRoute
  CaseCaseIdRoadmapRoute: typeof CaseCaseIdRoadmapRoute
  CaseCaseIdIndexRoute: typeof CaseCaseIdIndexRoute
}

const CaseCaseIdRouteRouteChildren: CaseCaseIdRouteRouteChildren = {
  CaseCaseIdChatRoute: CaseCaseIdChatRoute,
  CaseCaseIdDossierRoute: CaseCaseIdDossierRoute,
  CaseCaseIdInboxRoute: CaseCaseIdInboxRoute,
  CaseCaseIdLedgerRoute: CaseCaseIdLedgerRoute,
  CaseCaseIdMandateRoute: CaseCaseIdMandateRoute,
  CaseCaseIdRoadmapRoute: CaseCaseIdRoadmapRoute,
  CaseCaseIdIndexRoute: CaseCaseIdIndexRoute,
}

const CaseCaseIdRouteRouteWithChildren = CaseCaseIdRouteRoute._addFileChildren(
  CaseCaseIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaseCaseIdRouteRoute: CaseCaseIdRouteRouteWithChildren,
  IntakeCompanyOrganizationIdRoute: IntakeCompanyOrganizationIdRoute,
  IntakeProductProductIdRoute: IntakeProductProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
